---
- hosts: all
  remote_user: ${REMOTE_USERNAME}
  become: true

  tasks:

  # Create Portainer Data Volume
  - name: Create new Volume
    community.docker.docker_volume:
      name: portainer-data

  # Deploy Portainer
  - name: Deploy Portainer
    community.docker.docker_container:
      name: portainer
      image: "docker.io/portainer/portainer-ce"
      ports:
        - "9443:9443"
        - "8000:8000"

      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - portainer-data:/data
      restart_policy: always

  # Restart Portainer
  - name: Restart service Portainer, after installation
    community.docker.docker_container:
      name: portainer
      restart: true